[package]
name = "aws-sso-navigator"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1"
dirs = "5"
clap = { version = "4", features = ["derive"]}
skim = "0.10"
serde = { version = "1", features = ["derive"]}
toml = "0.8"

[dev-dependencies]
tempfile = "3"